# Generated by Django 3.2.8 on 2021-10-22 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='File',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
