# Generated by Django 3.2.8 on 2021-10-22 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211022_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 10, 22, 9, 29, 29, 840778, tzinfo=utc))),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
