# Generated by Django 3.2.8 on 2021-10-22 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211022_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 9, 36, 51, 919162, tzinfo=utc)),
        ),
    ]
