# Generated by Django 3.2.8 on 2021-10-22 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_uploadform_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadform',
            old_name='file',
            new_name='arquivo',
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 9, 41, 37, 222280, tzinfo=utc)),
        ),
    ]
