# Generated by Django 3.2.8 on 2021-10-22 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211022_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='arquivo',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 10, 48, 9, 872218, tzinfo=utc)),
        ),
    ]
