# Generated by Django 3.2.8 on 2021-10-22 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211022_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 10, 54, 6, 964216, tzinfo=utc)),
        ),
    ]
