# Generated by Django 3.2.8 on 2021-10-22 16:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211022_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransacoesEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=100)),
                ('Natureza', models.CharField(max_length=50)),
                ('Sinal', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['Descricao'],
            },
        ),
        migrations.CreateModel(
            name='TransacoesImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=1)),
                ('Data', models.CharField(max_length=8)),
                ('Valor', models.CharField(max_length=10)),
                ('CPF', models.CharField(max_length=11)),
                ('Cartao', models.CharField(max_length=12)),
                ('Hora', models.CharField(max_length=6)),
                ('Dono_da_Loja', models.CharField(max_length=14)),
                ('Nome_da_loja', models.CharField(max_length=19)),
            ],
            options={
                'ordering': ['Tipo'],
            },
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 16, 23, 29, 412566, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TransacoesEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Valor', models.CharField(max_length=10)),
                ('CPF', models.CharField(max_length=11)),
                ('Cartao', models.CharField(max_length=12)),
                ('Hora', models.TimeField()),
                ('Dono_da_Loja', models.CharField(max_length=14)),
                ('Nome_da_loja', models.CharField(max_length=19)),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipotransacoesentity')),
            ],
            options={
                'ordering': ['Tipo'],
            },
        ),
    ]
