# Generated by Django 3.2.8 on 2021-10-25 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211022_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 11, 12, 17, 910290, tzinfo=utc)),
        ),
    ]
