# Generated by Django 3.2.8 on 2021-10-25 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_uploadform_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipotransacoesentity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transacoesentity',
            options={},
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 11, 41, 54, 230325, tzinfo=utc)),
        ),
    ]
