# Generated by Django 3.2.8 on 2021-10-26 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import myapp.functions


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20211025_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='arquivo',
            field=models.FileField(upload_to='media', validators=[myapp.functions.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 7, 1, 0, 724760, tzinfo=utc)),
        ),
    ]
