# Generated by Django 3.2.8 on 2021-10-26 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_uploadform_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoesentity',
            name='Total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 8, 22, 56, 186112, tzinfo=utc)),
        ),
    ]
