# Generated by Django 3.2.8 on 2021-10-26 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20211026_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoesentity',
            name='Total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 8, 41, 20, 515710, tzinfo=utc)),
        ),
    ]
