# Generated by Django 3.2.8 on 2021-10-26 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20211026_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoesentity',
            name='Total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 21, 14, 12, 386279, tzinfo=utc)),
        ),
    ]
